query {
  team(slug: "${team}") {
    projects { edges { node {
      title
      project_medias { edges { node {
        user {
          id
          name
        }
        created_at
        report_type
        metadata
        last_status
        media {
          quote
          picture
          url
          embed
        }
        tags { edges { node {
          tag_text
        }}}
        tasks { edges { node {
          annotator {
            user {
              id
              name
            }
          }
          created_at
          label
          status
          first_response {
            annotator {
              user {
                id
                name
              }
            }
            created_at
            content
          }
          log { edges { node {
            annotation {
              annotator {
                user {
                  id
                  name
                }
              }
              created_at
              content
            }
            event_type
          }}}
        }}}
        comments: annotations(annotation_type: "comment") { edges { node {
          annotator {
            user {
              id
              name
            }
          }
          created_at
          content
        }}}
        log { edges { node {
          created_at
          user {
            id
          }
          event_type
        }}}
      }}}
    }}}
  }
}
